### ISSUE TITLE
Decision making paradigm

### ISSUE THREAD

**Issue by surrealbytes** [dellitsni/Konsent#24] opened 2018-03-17 18:49 UTC
After a brief research there seem to be a lot of [decision-making paradigms](https://en.wikipedia.org/wiki/Decision-making#Decision-making_techniques). At this moment majority-voting is implemented as part of phase2. We should consider the arguments people made about implementing a [consensus decision-making paradigm](https://theanarchistlibrary.org/library/seeds-for-change-consensus-decision-making) and which implications this might have with the implementation. We could try and make the phases abstract enough so users/unions can choose and pick which one they want or choose a specific paradigm and build on that.

**Comment by dellitsni** [comment] 2018-03-20 18:15
I agree that phase two needs a major overhaul, we should probably be discussing this elsewhere though, since it isn't directly related to the codebase. Maybe we could ask the Raddle community what they think, and work out a solution over there? Bring along that link to theanarchistlibrary, very relevant and well-written. 

@surrealbytes

**Comment by surrealbytes** [comment] 2018-03-23 19:19
Yea let's take this on raddle with the rest of the community, github is out of reach.
we can keep this open for implementation specific stuff.

**Comment by dellitsni** [comment] 2018-03-26 18:05
@surrealbytes What do you think about this approach:

> We could add a new phase between what's currently phase 2 and phase 1. This would be a simple discussion phase, similar to discussion on Raddle. Nested comments, perhaps votes, you get the idea. After a set amount of time, or after enough community members have agreed that discussion is finished, the issue will move to what is now phase 2 and would become phase 3, and things would proceed as usual. The discussion from phase 2 would be archived and accessible from phase 3.

I think this would give a balance between concensus and direct democracy, and thanks to the veto feature, minorities would still be respected. I also think this approach would reduce the amount of vetoes put in place drastically, because people can listen to each other and discuss the issue at hand before going straight to attempting to solve it.

**Comment by surrealbytes** [comment] 2018-03-26 19:09
I was thinking about how the discussion would happen in case there is no consensus but it fits to this as well. If the discussion is to take place in konsent this would mean we have to implement a minimum raddle like functionality which is not something trivial. How about leaving out the discussion part to other means, that can even be over voice or chat, and add some info fields like "issue metadata" that one can post links to matrix/raddle etc. where the discussion will happen?

I feel that the consensus model is easier to implement with regard to time and other heuristics. Everyone must consent in order for the issue to move phases or for a solution to pass, how this will happen konsent doesn't have to know. This also prevents konsent for being a single point of failure for the discussion data security/availability.

**Comment by dellitsni** [comment] 2018-03-29 16:08
@surrealbytes I think that's a great idea, there's plenty of much more refined communications solutions, and there's no need to mutate Konsent further. The current semi-lightweight model is probably best. How about this pretty simple solution:

During Phase Two, everyone is free to add links to external discussion platforms. Discussion will happen alongside solution proposals and can continue until the issue is closed. In case the issue is vetoed, it can be discussed here until someone reopens it.

**Comment by dellitsni** [comment] 2018-04-06 21:46
Closing in favor of [this](https://raddle.me/f/konsent/28848/decision-making-paradigm) thread on Raddle.

**Closed by dellitsni** 2018-04-06 21:46 UTC
Labels: discussion
